### ISSUE TITLE
Filename too long

### ISSUE THREAD

**Issue by zombor** [dayflower/rack-session-file#1]
Trying to use this, but I get this error:

```
  File name too long - /tmp/BAh7CEkiCm9hdXRoBjoGRUZ7BjoJY29kZUkiAdhBUUJxNVQtaHRSYTlSQzFz
  eEZ0WUFaNXFRUXJMM254ejZLS0NOUnBRX2xVbndZTEpOZWoxX2NjZ0dfVHFN
  ODd6Sjk5NFk3U2NnRUw2eWdRVUpnMkthZkxLMk0wb25HZEFBVlFoWWllNUJG
  QnJJc3R5NVpQSnpWYWVBUlpLRHpOXy1YVVhWV1hxQUVyTndHZmRsS2h5ak80
  T2R0cDFEWTRZSTV5enJtczRqT2V2Q3NxdlFaZ2JuckRSVGszVkYzeXVkNmlF
  UXA0QmdGR3k3ZXkwcVdKZ2k0dlQGOwBUSSIMY2xhaW1lZAY7AEZUSSIPc2Vz
  c2lvbl9pZAY7AEYiRTMyYjg4NmI1ZGI2MTE0MWQzZDI4MGU3ODk1YmU0ODQ2
  ZTc2ZWE0ZjI3ZWY1NWU4NjAxMjI0NDBhYzNmYmYzNWY=
  --c1e42082830cb694e25a782c3a843470adbf01b1 (Errno::ENAMETOOLONG)
  /usr/lib/ruby/1.9.1/pstore.rb:365:in `initialize'
  /usr/lib/ruby/1.9.1/pstore.rb:365:in `new'
  /usr/lib/ruby/1.9.1/pstore.rb:365:in `open_and_lock_file'
  /usr/lib/ruby/1.9.1/pstore.rb:319:in `block in transaction'
  <internal:prelude>:10:in `synchronize'
  /usr/lib/ruby/1.9.1/pstore.rb:316:in `transaction'
  ./app/controllers/invites.rb:41:in `block (2 levels) in <top (required)>'
```

**Comment by dayflower** [comment]
Hmm...
Length of session ID seems to be very long.  I do not know the reason why such lengthy ID was used.

Do you use this module with Rails 3?
If so, please try updated version 0.4.0 (added companion module for Rails 3).
Usage with Rails 3 apps is written in `README.md`.

**Comment by zombor** [comment]
It's a padrino app.

**Comment by dayflower** [comment]
OK, I see.

GUIDE: Comment out all `enable :session` in your app.
`enable :session` may be written in `config/app.rb`, `app/app.rb`, and `admin/app.rb` if you use admin generator.

MECH:
Padrino(Sinatra)'s `enable :session` token will activate `Rack::Session::Cookie` as session backend.  Backend is not selectable and configuable in such situation.  `Rack::Session::Cookie` cannot be used in conjunction with `Rack::Session::File` (and any other Rack session middlewares).
With enabling `Rack::Session::File` (and any other) via `use Rack::Session::File` syntax, you can still use `session[foobar]` in your app even if you disable Padrino(Sinatra)'s builtin session feature with `disable :session`.

**Comment by zombor** [comment]
Ah, I see. That seems to work.

**Comment by dayflower** [comment]
Thanks for your report.
I'm going to update the document on next release.
