### ISSUE TITLE
Juno session store

### ISSUE THREAD

**Issue by minad** [dayflower/rack-session-file#2]
Hi,

you might be interested in https://github.com/minad/juno which supports a file based rack session store.

Daniel

**Comment by dayflower** [comment]
Thanks for your recommendation.
Looks wonderful product.
Migration between different backends seems to be easy.

I'm going to continue to use this rack-session-file on my sandbox-level (mock-up) projects in future,
but I'll consider Juno as candidates of session store on projects in production phase.
